Add embed option exportDataSet to set the data used when opening source/opening in editor
vega/vega-embed pull request #720
Opened 2021-07-20 22:42 UTC by mcintyre94

Closes #719 

This PR adds a new optional embed option `exportDataSet`. If it is set, then when the "Open Source" and "Open in Vega Editor" actions are used the data set given is used as the `data.values` of the spec before it is opened.

This means that it is possible to use Vega's changeset functionality to modify the data, and then open source/editor to eg. extract the latest data or to iterate on the chart in the editor with the latest data available.

I've also added an example file `test-changeset.html` which demonstrates this feature (and changesets more widely). This is based on the streaming demo: https://vega.github.io/vega-lite/tutorials/streaming.html 

Here's a short video showing this working. Note that without this PR the data would be empty in both cases and the editor wouldn't render any data. 

https://user-images.githubusercontent.com/1711350/126404545-c371a801-35a9-4044-b749-6567d47561d7.mov

2021-07-20 23:18 UTC, domoritz requested changes
Thanks for the pull request. I think this solution is too brittle as it only works for Vega-Lite. 

Instead, we should send the view state via postMessage to the editor.

2021-07-21 06:37 UTC, mcintyre94 commented
> Instead, we should send the view state via postMessage to the editor.

Thanks for taking a look! Isn't this what the `post` function that I'm sending the data in is already doing though? It looks like its implementation is opening the editor window and then sending the data with `postMessage`. Are you saying that it should send the spec unmodified, and then send a secondary message to update it? Or am I updating the wrong thing by updating the `spec`?

2021-07-21 17:41 UTC, mcintyre94 commented
I've just pushed an updated version which does at least work with `test-vg.html`:

- The `data` pushed to the editor now has a name as well as the values
- When `mode` is `vega`, the data is put in an array of length 1. When it's `vegalite` it stays as an object. 

Hopefully this makes it less brittle, but I'm happy to change the way it sends the message to the editor as you mentioned - I'm just not clear exactly what I need to change there yet.

2021-07-21 17:46 UTC, domoritz requested changes
This isn't an easy issue so I don't want you to get too hung up when working on it and I will help where I can. 

When I say send the state, I mean use https://vega.github.io/vega/docs/api/view/#view_getState in embed and https://vega.github.io/vega/docs/api/view/#view_setState in the editor. You will need to send a pull request to the editor as well. 

I had issues with serializing state before so maybe we also need to change Vega to make this approach work.

2021-07-21 17:46 UTC, domoritz commented on src/embed.ts
> +    exportSpec.data = exportSpecData;
Data can be nested in a spec so this code won't work in general.

2021-09-17 01:34 UTC, domoritz commented
Please send a new pull request.

2021-09-17 01:34 UTC, closed without merging