Add a logger to embed init options
vega/vega-embed pull request #732
Opened 2021-08-04 14:25 UTC by challet

Add an option to the `embed` function. 
It allows to pass a custom logger to the view.

2021-08-05 04:46 UTC, domoritz commented on src/embed.ts
> +  logger as VgLogger,
```suggestion
  logger as vegaLogger,
```

2021-08-05 04:49 UTC, domoritz requested changes
We should also pass the logger to Vega-Lite. 

Please add a test as well.

2021-08-05 04:49 UTC, domoritz commented on README.md
> +| `logger`      | Object        | Sets a custom logger handler. See [Vega docs](https://vega.github.io/vega/docs/api/view/#view_logger) for details. It must follow the interface of [the original one]
```suggestion
| `logger`      | Object        | Sets a [custom logger handler on the view](https://vega.github.io/vega/docs/api/view/#view_logger). A logger must implement the [Vega logger API](https://github.com/vega/vega/tree/master/packages/vega-util#logger). |
```

2021-08-05 15:37 UTC, challet commented
> We should also pass the logger to Vega-Lite.

Isn't it already done since the part that adds the logger works with both Vega and Vega-Lite specs ? The mode having been guessed a few lines before.

2021-09-17 01:39 UTC, domoritz commented
I don't think it is. We call `compile` in the preprocessor in https://github.com/vega/vega-embed/pull/732/files#diff-b0761852e43b4566f7d72f8bc18bc1a7fd5db43c5ad1d9dfcc4529afe86d0174R108. But we are not passing the logger in (docs at https://vega.github.io/vega-lite/usage/compile.html#javascript). Could you update the code to make it work? I think the best would probably be to remove the preprocessor variable and just conditionally call vl.compile on the spec.

2022-01-20 01:52 UTC, domoritz commented
@challet can you finish up the pull request?

2022-01-31 17:22 UTC, challet commented on src/embed.ts
> +  let vgSpec: VgSpec = PREPROCESSOR[mode](spec, { ...config, logger });
Can be added directly to the passed config, since the whole arg will be discarded when the mode is not 'vega-lite'

2022-01-31 17:23 UTC, challet commented
@domoritz sorry it went out of my scope. I haven't added a test for the last change though.

2022-02-01 02:03 UTC, domoritz commented
Thank you. Can you make sure the test pass?

2022-02-09 22:57 UTC, domoritz commented
Ping @challet

2022-02-09 23:51 UTC, challet commented
Sorry, I will have a look in the next days.

2025-02-07 20:41 UTC, domoritz commented
Closing due to inactivity. Please make a new pull request.

2025-02-07 20:41 UTC, closed without merging